### PR TITLE
Installation generator

### PR DESCRIPTION
**Pull request by avdgaag**
This replaces installation instructions with a Thor generator to copy relevant files into the current directory.

### CODE REVIEW

**Comment by stefanroex** [comment]
Looked through the code a few times and it looks really solid.

I'm only wondering whether we should release this as a Rubygem? It seems troublesome to clone the repo and call the generator from within the repo. What where your considerations?

**Comment by stefanroex** [comment]
Oh, I do have a suggestion. In one of our projects you included a `.bundlerauditignore` file. I think other projects could benefit from that as well.

**Comment by avdgaag** [comment]
> I'm only wondering whether we should release this as a Rubygem?

I guess we _could_ release it as a gem, but then you'd have to make gem releases when things change and all that. It doesn't feel like a gem to me; to me it's just a repo with some templates and a script that happens to be written in Ruby. Maybe releasing it as a gem even wrongfully gives the impression you should add it to your Gemfile, or that it's only applicable to Ruby projects…

**Comment by avdgaag** [comment]
> In one of our projects you included a .bundlerauditignore file. I think other projects could benefit from that as well.

Right, I'll add that.

**Comment by florish** [comment]
@avdgaag @stefanroex Great improvement! About whether or not to make this a gem: making it a gem does not necessarily mean we need to publish the gem to rubygems.org. If jou use bundler's gem generator script, you can add a binary to the gemspec, simply `git pull` or `git clone` the styleguide repository and then run `rake install`. Instead of having to do this:

```
$ cd /path/to/project
$ /path/to/styleguide rubocop
```

You can simply type this:

```
$ cd path/to/project
$ styleguide rubocop
```

**Comment by avdgaag** [comment]
> making it a gem does not necessarily mean we need to publish the gem to rubygems.org

True, but it seems a roundabout way just to get an executable on your PATH. Regardless, I'm not _against_ it — so go ahead and make a PR :smile:

**Comment by florish** [comment]
Yep, it might be a bit too much. I'll just `ln -s` in `bin` directory to save me from typing the full path.

**Pull request merged**
